[package]
name = "aurae-ebpf-shared"
version = "0.0.0"
publish = false
edition = "2021"
authors = ["The Aurae Authors", "Kris NÃ³va <kris@nivenly.com>"]
license = "Apache-2.0"

[features]
default = []
user = [ "aya" ]

[dependencies]
aya = { version = ">=0.11", optional=true }

[lib]
path = "src/lib.rs"